/**
 * lyrie-action runner — unit tests for pure helpers (severity ranking,
 * SARIF rendering, Markdown rendering).
 *
 * The full runner is exercised end-to-end in
 * `.github/workflows/action-selftest.yml` (the action runs against the
 * Lyrie repo itself on every PR).
 *
 * © OTT Cybersecurity LLC — https://lyrie.ai
 */

import { describe, expect, test } from "bun:test";

// We re-export internal helpers through a small bridge for testing without
// changing the runner script's CLI shape.
import {
  countBySeverity,
  renderMarkdown,
  renderSarif,
  type Finding,
  type ScanResult,
} from "./runner-helpers";

const sample: ScanResult = {
  scanMode: "quick",
  target: "./",
  startedAt: "2026-04-27T13:00:00.000Z",
  finishedAt: "2026-04-27T13:00:42.000Z",
  shielded: 1,
  findings: [
    {
      id: "lyrie-shield-1",
      title: "Shield: prompt-injection pattern in recalled content",
      severity: "high",
      description: "Detected a known injection pattern in src/foo.ts.",
      file: "src/foo.ts",
      line: 42,
      cwe: "CWE-1188",
      remediation: "Remove the flagged content or mark with an exception.",
    },
    {
      id: "lyrie-shield-2",
      title: "Shield: secret-like material",
      severity: "critical",
      description: "Found PEM-style private key block.",
      file: ".env.example",
      cwe: "CWE-798",
    },
    {
      id: "lyrie-shield-3",
      title: "Low note",
      severity: "low",
      description: "Style nit.",
    },
  ],
};

describe("countBySeverity", () => {
  test("counts each level", () => {
    const c = countBySeverity(sample.findings);
    expect(c.critical).toBe(1);
    expect(c.high).toBe(1);
    expect(c.low).toBe(1);
    expect(c.medium).toBe(0);
  });

  test("zero counts on empty input", () => {
    expect(countBySeverity([] as Finding[])).toEqual({
      critical: 0,
      high: 0,
      medium: 0,
      low: 0,
      info: 0,
    });
  });
});

describe("renderMarkdown", () => {
  test("renders a clean-bill summary when no findings", () => {
    const md = renderMarkdown({ ...sample, findings: [], shielded: 0 });
    expect(md).toContain("Lyrie Pentest Report");
    expect(md).toContain("clean bill of health");
  });

  test("renders findings with severity badges and file refs", () => {
    const md = renderMarkdown(sample);
    expect(md).toContain("CRITICAL");
    expect(md).toContain("HIGH");
    expect(md).toContain("src/foo.ts");
    expect(md).toContain("CWE-1188");
    expect(md).toContain("Generated by");
  });
});

describe("renderSarif", () => {
  test("produces a SARIF 2.1.0 schema log", () => {
    const log = renderSarif(sample);
    expect(log.$schema).toContain("sarif-2.1.0");
    expect(log.version).toBe("2.1.0");
    expect(log.runs).toHaveLength(1);
  });

  test("maps severity to SARIF level correctly", () => {
    const log = renderSarif(sample);
    const results = log.runs[0].results;
    const crit = results.find((r) => r.ruleId === "lyrie-shield-2");
    const high = results.find((r) => r.ruleId === "lyrie-shield-1");
    const low = results.find((r) => r.ruleId === "lyrie-shield-3");
    expect(crit?.level).toBe("error");
    expect(high?.level).toBe("error");
    expect(low?.level).toBe("note");
  });

  test("includes file location when present", () => {
    const log = renderSarif(sample);
    const high = log.runs[0].results.find((r) => r.ruleId === "lyrie-shield-1");
    expect(high?.locations?.[0]?.physicalLocation.artifactLocation.uri).toBe("src/foo.ts");
    expect(high?.locations?.[0]?.physicalLocation.region?.startLine).toBe(42);
  });

  test("rules are deduplicated by id", () => {
    const dup: ScanResult = {
      ...sample,
      findings: [
        ...sample.findings,
        { ...sample.findings[0], description: "another" },
      ],
    };
    const log = renderSarif(dup);
    expect(log.runs[0].tool.driver.rules.length).toBe(3);
  });
});
