/**
 * Pure helpers used by the lyrie-action runner — kept separate so they're
 * testable without spawning a full GitHub Actions environment.
 *
 * © OTT Cybersecurity LLC — https://lyrie.ai
 */

export interface Finding {
  id: string;
  title: string;
  severity: "info" | "low" | "medium" | "high" | "critical";
  description: string;
  file?: string;
  line?: number;
  cwe?: string;
  remediation?: string;
}

export interface ScanResult {
  scanMode: string;
  target: string;
  startedAt: string;
  finishedAt: string;
  findings: Finding[];
  shielded: number;
}

export const SEVERITY_RANK: Record<string, number> = {
  none: -1,
  info: 0,
  low: 1,
  medium: 2,
  high: 3,
  critical: 4,
};

export function countBySeverity(findings: Finding[]) {
  const c = { critical: 0, high: 0, medium: 0, low: 0, info: 0 };
  for (const f of findings) c[f.severity] = (c[f.severity] ?? 0) + 1;
  return c;
}

function badge(sev: string): string {
  switch (sev) {
    case "critical": return "🟥 **CRITICAL**";
    case "high":     return "🟧 **HIGH**";
    case "medium":   return "🟨 **MEDIUM**";
    case "low":      return "🟩 **LOW**";
    default:         return "⬜ **INFO**";
  }
}

export function renderMarkdown(r: ScanResult): string {
  const counts = countBySeverity(r.findings);
  const lines: string[] = [
    "# 🛡️ Lyrie Pentest Report",
    "",
    `- **Mode:** \`${r.scanMode}\``,
    `- **Target:** \`${r.target}\``,
    `- **Started:** ${r.startedAt}`,
    `- **Finished:** ${r.finishedAt}`,
    `- **Findings:** ${r.findings.length}` +
      ` (critical ${counts.critical}, high ${counts.high}, medium ${counts.medium}, low ${counts.low})`,
    "",
  ];

  if (r.findings.length === 0) {
    lines.push("✅ **No findings — Lyrie Shield gave this clean bill of health.**");
    lines.push("");
  } else {
    for (const f of r.findings) {
      lines.push(`## ${badge(f.severity)} ${f.title}`);
      lines.push("");
      if (f.file) lines.push(`- **File:** \`${f.file}\`${f.line ? `:${f.line}` : ""}`);
      if (f.cwe) lines.push(`- **CWE:** ${f.cwe}`);
      lines.push("");
      lines.push(f.description);
      if (f.remediation) {
        lines.push("");
        lines.push(`**Remediation:** ${f.remediation}`);
      }
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("Generated by [Lyrie Agent](https://lyrie.ai) · MIT-licensed.");
  return lines.join("\n");
}

export interface SarifLog {
  $schema: string;
  version: "2.1.0";
  runs: Array<{
    tool: {
      driver: {
        name: string;
        informationUri: string;
        version: string;
        rules: Array<{
          id: string;
          name: string;
          shortDescription: { text: string };
          helpUri: string;
        }>;
      };
    };
    results: Array<{
      ruleId: string;
      level: "warning" | "error" | "note";
      message: { text: string };
      locations?: Array<{
        physicalLocation: {
          artifactLocation: { uri: string };
          region?: { startLine: number };
        };
      }>;
    }>;
  }>;
}

export function renderSarif(r: ScanResult): SarifLog {
  const rules = new Map<string, SarifLog["runs"][0]["tool"]["driver"]["rules"][0]>();
  const results: SarifLog["runs"][0]["results"] = [];
  for (const f of r.findings) {
    const ruleId = f.id;
    if (!rules.has(ruleId)) {
      rules.set(ruleId, {
        id: ruleId,
        name: f.title,
        shortDescription: { text: f.title },
        helpUri: "https://lyrie.ai/docs/findings/" + ruleId,
      });
    }
    const level = f.severity === "critical" || f.severity === "high"
      ? "error"
      : f.severity === "medium"
        ? "warning"
        : "note";
    results.push({
      ruleId,
      level,
      message: { text: f.description },
      locations: f.file
        ? [{
            physicalLocation: {
              artifactLocation: { uri: f.file },
              region: f.line ? { startLine: f.line } : undefined,
            },
          }]
        : undefined,
    });
  }

  return {
    $schema: "https://json.schemastore.org/sarif-2.1.0.json",
    version: "2.1.0",
    runs: [{
      tool: {
        driver: {
          name: "Lyrie Pentest",
          informationUri: "https://lyrie.ai",
          version: "0.2.0",
          rules: Array.from(rules.values()),
        },
      },
      results,
    }],
  };
}
