/**
 * Lyrie Tools Catalog — built-in registry.
 *
 * Lyrie.ai by OTT Cybersecurity LLC — https://lyrie.ai — MIT License.
 *
 * Lyrie-vetted entries only. Phishing kits, mass DDoS launchers, RATs,
 * jammers, and deauthers are intentionally excluded — they don't fit
 * an enterprise security platform's brand.
 *
 * Each entry catalogs an external tool Lyrie can drive, NOT a tool
 * Lyrie ships. Lyrie doesn't bundle these binaries; the catalog gives
 * the agent and operators install commands, install detection, and
 * recommendation-by-intent.
 */

import type { ToolDefinition } from "./types";

export const BUILTIN_TOOLS: ReadonlyArray<ToolDefinition> = [
  // ─── Information Gathering ────────────────────────────────────────────────
  {
    id: "nmap",
    name: "Nmap",
    description: "Network discovery and port-scanning workhorse.",
    homepage: "https://github.com/nmap/nmap",
    license: "NPSL",
    category: "information-gathering",
    tags: ["scanner", "osint"],
    install: { kind: "system", command: "brew install nmap || apt install -y nmap", detect: "nmap", versionFlag: "--version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["scan a network", "find open ports", "map a host", "service fingerprint"],
  },
  {
    id: "amass",
    name: "Amass",
    description: "Active and passive subdomain enumeration with attack-surface mapping.",
    homepage: "https://github.com/owasp-amass/amass",
    license: "Apache-2.0",
    category: "information-gathering",
    tags: ["osint", "scanner", "web"],
    install: { kind: "go", command: "go install -v github.com/owasp-amass/amass/v4/...@master", detect: "amass", versionFlag: "version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["find subdomains", "map attack surface", "enumerate dns"],
  },
  {
    id: "subfinder",
    name: "Subfinder",
    description: "Fast passive subdomain enumeration via 30+ sources.",
    homepage: "https://github.com/projectdiscovery/subfinder",
    license: "MIT",
    category: "information-gathering",
    tags: ["osint", "scanner"],
    install: { kind: "go", command: "go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest", detect: "subfinder", versionFlag: "-version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["find subdomains", "passive recon"],
  },
  {
    id: "httpx",
    name: "httpx",
    description: "Fast, multi-purpose HTTP toolkit for probing and fingerprinting.",
    homepage: "https://github.com/projectdiscovery/httpx",
    license: "MIT",
    category: "information-gathering",
    tags: ["scanner", "web", "api"],
    install: { kind: "go", command: "go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest", detect: "httpx", versionFlag: "-version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["probe http endpoints", "fingerprint web servers", "check live hosts"],
  },
  {
    id: "katana",
    name: "Katana",
    description: "Next-generation crawling and spidering framework.",
    homepage: "https://github.com/projectdiscovery/katana",
    license: "MIT",
    category: "information-gathering",
    tags: ["scanner", "web", "fuzzer"],
    install: { kind: "go", command: "go install github.com/projectdiscovery/katana/cmd/katana@latest", detect: "katana", versionFlag: "-version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["crawl a website", "discover endpoints", "map web app"],
  },
  {
    id: "theharvester",
    name: "theHarvester",
    description: "OSINT email, subdomain, and metadata harvester.",
    homepage: "https://github.com/laramies/theHarvester",
    license: "GPL-2.0",
    category: "information-gathering",
    tags: ["osint"],
    install: { kind: "pipx", command: "pipx install theHarvester", detect: "theHarvester" },
    supportedOS: ["linux", "macos"],
    intents: ["find emails", "osint a domain", "scrape contact info"],
  },
  {
    id: "spiderfoot",
    name: "SpiderFoot",
    description: "Automated OSINT collection across 200+ data sources.",
    homepage: "https://github.com/smicallef/spiderfoot",
    license: "MIT",
    category: "information-gathering",
    tags: ["osint", "intel"],
    install: { kind: "git", command: "git clone https://github.com/smicallef/spiderfoot && pip install -r spiderfoot/requirements.txt", detect: "spiderfoot" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["full osint sweep", "automated intel"],
  },
  {
    id: "shodan-cli",
    name: "Shodan CLI",
    description: "Command-line interface to the Shodan internet-wide scan dataset.",
    homepage: "https://github.com/achillean/shodan-python",
    license: "MIT",
    category: "information-gathering",
    tags: ["osint", "intel", "scanner"],
    install: { kind: "pip", command: "pip install shodan", detect: "shodan" },
    supportedOS: ["any"],
    intents: ["search shodan", "find exposed services"],
  },

  // ─── Web Attack / Fuzzing ────────────────────────────────────────────────
  {
    id: "nuclei",
    name: "Nuclei",
    description: "Template-based vulnerability scanner with a community library of 9,000+ checks.",
    homepage: "https://github.com/projectdiscovery/nuclei",
    license: "MIT",
    category: "web-attack",
    tags: ["scanner", "web", "api", "dynamic"],
    install: { kind: "go", command: "go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest", detect: "nuclei", versionFlag: "-version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["scan for cves", "template-based scan", "find known vulns", "kubernetes security"],
  },
  {
    id: "ffuf",
    name: "ffuf",
    description: "Fast web fuzzer for content discovery, parameters, and virtual hosts.",
    homepage: "https://github.com/ffuf/ffuf",
    license: "MIT",
    category: "fuzzing",
    tags: ["fuzzer", "web"],
    install: { kind: "go", command: "go install github.com/ffuf/ffuf/v2@latest", detect: "ffuf", versionFlag: "-V" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["fuzz a web app", "directory discovery", "parameter fuzzing"],
  },
  {
    id: "feroxbuster",
    name: "Feroxbuster",
    description: "Recursive content discovery with intelligent backoff.",
    homepage: "https://github.com/epi052/feroxbuster",
    license: "MIT",
    category: "fuzzing",
    tags: ["fuzzer", "web"],
    install: { kind: "cargo", command: "cargo install feroxbuster", detect: "feroxbuster", versionFlag: "--version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["recursive directory discovery"],
  },
  {
    id: "gobuster",
    name: "Gobuster",
    description: "Directory, DNS, and vhost brute-forcer.",
    homepage: "https://github.com/OJ/gobuster",
    license: "Apache-2.0",
    category: "fuzzing",
    tags: ["fuzzer", "web"],
    install: { kind: "go", command: "go install github.com/OJ/gobuster/v3@latest", detect: "gobuster", versionFlag: "version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["brute force directories", "dns brute force"],
  },
  {
    id: "dirsearch",
    name: "Dirsearch",
    description: "Multi-purpose web path scanner.",
    homepage: "https://github.com/maurosoria/dirsearch",
    license: "GPL-2.0",
    category: "fuzzing",
    tags: ["fuzzer", "web"],
    install: { kind: "pip", command: "pip install dirsearch", detect: "dirsearch" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["directory discovery"],
  },
  {
    id: "sqlmap",
    name: "sqlmap",
    description: "Automated SQL injection and database takeover tool (authorized targets only).",
    homepage: "https://github.com/sqlmapproject/sqlmap",
    license: "GPL-2.0",
    category: "sql-injection",
    tags: ["scanner", "web", "dynamic"],
    install: { kind: "git", command: "git clone --depth 1 https://github.com/sqlmapproject/sqlmap", detect: "sqlmap" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["test sqli", "database takeover (authorized)"],
  },
  {
    id: "nikto",
    name: "Nikto",
    description: "Web-server scanner that checks 6,700+ potentially dangerous files / programs.",
    homepage: "https://github.com/sullo/nikto",
    license: "GPL-2.0",
    category: "web-attack",
    tags: ["scanner", "web"],
    install: { kind: "system", command: "apt install -y nikto || brew install nikto", detect: "nikto" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["scan a web server", "default credential check"],
  },
  {
    id: "wafw00f",
    name: "wafw00f",
    description: "Identifies and fingerprints Web Application Firewalls.",
    homepage: "https://github.com/EnableSecurity/wafw00f",
    license: "BSD-3-Clause",
    category: "web-attack",
    tags: ["scanner", "web"],
    install: { kind: "pip", command: "pip install wafw00f", detect: "wafw00f" },
    supportedOS: ["any"],
    intents: ["fingerprint waf", "detect cloudflare/akamai"],
  },
  {
    id: "zaproxy",
    name: "OWASP ZAP",
    description: "OWASP-maintained web application security scanner and proxy.",
    homepage: "https://github.com/zaproxy/zaproxy",
    license: "Apache-2.0",
    category: "web-attack",
    tags: ["scanner", "web", "dynamic"],
    install: { kind: "system", command: "brew install --cask owasp-zap || apt install -y zaproxy", detect: "zap.sh" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["full web app scan", "owasp top 10"],
  },
  {
    id: "arjun",
    name: "Arjun",
    description: "HTTP parameter discovery suite.",
    homepage: "https://github.com/s0md3v/Arjun",
    license: "AGPL-3.0",
    category: "web-attack",
    tags: ["fuzzer", "web", "api"],
    install: { kind: "pip", command: "pip install arjun", detect: "arjun" },
    supportedOS: ["any"],
    intents: ["find hidden parameters"],
  },

  // ─── XSS ──────────────────────────────────────────────────────────────────
  {
    id: "dalfox",
    name: "DalFox",
    description: "Powerful, fast XSS scanner and analyser.",
    homepage: "https://github.com/hahwul/dalfox",
    license: "MIT",
    category: "xss",
    tags: ["scanner", "web", "dynamic"],
    install: { kind: "go", command: "go install github.com/hahwul/dalfox/v2@latest", detect: "dalfox", versionFlag: "version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["test xss", "scan for cross site scripting"],
  },
  {
    id: "xsstrike",
    name: "XSStrike",
    description: "Advanced XSS detection suite with payload generator.",
    homepage: "https://github.com/s0md3v/XSStrike",
    license: "GPL-3.0",
    category: "xss",
    tags: ["scanner", "web"],
    install: { kind: "git", command: "git clone https://github.com/s0md3v/XSStrike", detect: "xsstrike" },
    supportedOS: ["any"],
    intents: ["xss detection"],
  },

  // ─── Secrets ─────────────────────────────────────────────────────────────
  {
    id: "gitleaks",
    name: "Gitleaks",
    description: "Detect hardcoded secrets in git repositories.",
    homepage: "https://github.com/gitleaks/gitleaks",
    license: "MIT",
    category: "secrets",
    tags: ["secrets", "scanner", "static"],
    install: { kind: "brew", command: "brew install gitleaks", detect: "gitleaks", versionFlag: "version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["scan for secrets in git", "find leaked credentials", "pre-commit secret check"],
  },
  {
    id: "trufflehog",
    name: "TruffleHog",
    description: "Find verified secrets across git history, files, S3, and more.",
    homepage: "https://github.com/trufflesecurity/trufflehog",
    license: "AGPL-3.0",
    category: "secrets",
    tags: ["secrets", "scanner", "static"],
    install: { kind: "brew", command: "brew install trufflehog", detect: "trufflehog" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["find verified secrets", "scan a git repo for credentials", "find hardcoded secrets mobile"],
  },

  // ─── Active Directory ───────────────────────────────────────────────────
  {
    id: "bloodhound",
    name: "BloodHound",
    description: "Reveals AD attack paths via graph analysis.",
    homepage: "https://github.com/SpecterOps/BloodHound",
    license: "Apache-2.0",
    category: "active-directory",
    tags: ["ad", "post-exploit"],
    install: { kind: "system", command: "see https://github.com/SpecterOps/BloodHound#installation", detect: "bloodhound" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["map ad attack paths", "find domain admin paths"],
  },
  {
    id: "netexec",
    name: "NetExec",
    description: "Network service enumeration and exploitation framework (formerly CrackMapExec).",
    homepage: "https://github.com/Pennyw0rth/NetExec",
    license: "BSD-2-Clause",
    category: "active-directory",
    tags: ["ad", "scanner"],
    install: { kind: "pipx", command: "pipx install git+https://github.com/Pennyw0rth/NetExec", detect: "nxc" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["enumerate smb", "test ad credentials"],
  },
  {
    id: "impacket",
    name: "Impacket",
    description: "Python classes for working with Windows network protocols (SMB, MSRPC, etc.).",
    homepage: "https://github.com/fortra/impacket",
    license: "Apache-1.1",
    category: "active-directory",
    tags: ["ad", "post-exploit"],
    install: { kind: "pipx", command: "pipx install impacket", detect: "GetUserSPNs.py" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["kerberoasting", "as-rep roasting", "smb enumeration"],
  },
  {
    id: "kerbrute",
    name: "Kerbrute",
    description: "Kerberos pre-auth user enumeration and password spraying.",
    homepage: "https://github.com/ropnop/kerbrute",
    license: "Apache-2.0",
    category: "active-directory",
    tags: ["ad", "scanner"],
    install: { kind: "go", command: "go install github.com/ropnop/kerbrute@latest", detect: "kerbrute" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["enumerate ad users", "kerberos password spray"],
  },

  // ─── Cloud Security ─────────────────────────────────────────────────────
  {
    id: "prowler",
    name: "Prowler",
    description: "AWS / GCP / Azure / K8s security posture assessment with 400+ checks.",
    homepage: "https://github.com/prowler-cloud/prowler",
    license: "Apache-2.0",
    category: "cloud-security",
    tags: ["cloud", "scanner", "iac"],
    install: { kind: "pipx", command: "pipx install prowler", detect: "prowler", versionFlag: "-v" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["audit aws", "cloud posture review", "cspm scan", "scan s3 bucket permissions", "check iam misconfiguration", "audit gcp roles", "azure security scan"],
  },
  {
    id: "scoutsuite",
    name: "ScoutSuite",
    description: "Multi-cloud security auditing tool by NCC Group.",
    homepage: "https://github.com/nccgroup/ScoutSuite",
    license: "GPL-2.0",
    category: "cloud-security",
    tags: ["cloud", "scanner"],
    install: { kind: "pipx", command: "pipx install scoutsuite", detect: "scout" },
    supportedOS: ["any"],
    intents: ["multi-cloud audit", "enumerate cloud resources", "check iam misconfiguration", "audit gcp roles", "azure security scan"],
  },
  {
    id: "trivy",
    name: "Trivy",
    description: "Vulnerability and misconfiguration scanner for containers, IaC, repos, and more.",
    homepage: "https://github.com/aquasecurity/trivy",
    license: "Apache-2.0",
    category: "container-security",
    tags: ["container", "iac", "scanner", "static"],
    install: { kind: "brew", command: "brew install trivy", detect: "trivy", versionFlag: "--version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["scan a container", "iac scan", "supply-chain audit", "kubernetes security"],
  },

  // ─── Mobile ──────────────────────────────────────────────────────────────
  {
    id: "mobsf",
    name: "MobSF",
    description: "Mobile Security Framework — automated iOS / Android / Windows app analysis.",
    homepage: "https://github.com/MobSF/Mobile-Security-Framework-MobSF",
    license: "GPL-3.0",
    category: "mobile-security",
    tags: ["mobile", "static", "dynamic"],
    install: { kind: "docker", command: "docker pull opensecurity/mobile-security-framework-mobsf", detect: "mobsf" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["scan android app", "ios app analysis", "mobile pentest", "mobile app security", "find hardcoded secrets mobile"],
  },
  {
    id: "frida",
    name: "Frida",
    description: "Dynamic instrumentation toolkit for developers, reverse-engineers, and security researchers.",
    homepage: "https://github.com/frida/frida",
    license: "wxWindows",
    category: "mobile-security",
    tags: ["mobile", "rev-eng", "dynamic"],
    install: { kind: "pipx", command: "pipx install frida-tools", detect: "frida" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["instrument a mobile app", "runtime hooking", "analyze ios ipa", "hook mobile app", "mobile app security"],
  },
  {
    id: "objection",
    name: "Objection",
    description: "Runtime mobile exploration toolkit powered by Frida.",
    homepage: "https://github.com/sensepost/objection",
    license: "GPL-3.0",
    category: "mobile-security",
    tags: ["mobile", "dynamic"],
    install: { kind: "pipx", command: "pipx install objection", detect: "objection" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["bypass ios pinning", "android runtime exploration", "analyze ios ipa", "hook mobile app"],
  },

  // ─── Reverse Engineering ────────────────────────────────────────────────
  {
    id: "ghidra",
    name: "Ghidra",
    description: "NSA-developed software reverse-engineering suite.",
    homepage: "https://github.com/NationalSecurityAgency/ghidra",
    license: "Apache-2.0",
    category: "reverse-engineering",
    tags: ["rev-eng"],
    install: { kind: "system", command: "see https://ghidra-sre.org/", detect: "ghidraRun" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["reverse engineer a binary", "decompile"],
  },
  {
    id: "radare2",
    name: "Radare2",
    description: "Unix-like reverse-engineering framework and command-line toolset.",
    homepage: "https://github.com/radareorg/radare2",
    license: "LGPL-3.0",
    category: "reverse-engineering",
    tags: ["rev-eng"],
    install: { kind: "brew", command: "brew install radare2", detect: "r2" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["disassemble", "binary analysis"],
  },
  {
    id: "jadx",
    name: "JadX",
    description: "Decompiler for Android APK, AAR, JAR, DEX.",
    homepage: "https://github.com/skylot/jadx",
    license: "Apache-2.0",
    category: "reverse-engineering",
    tags: ["rev-eng", "mobile"],
    install: { kind: "brew", command: "brew install jadx", detect: "jadx" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["decompile apk", "android source recovery", "analyze android app"],
  },
  {
    id: "apktool",
    name: "Apktool",
    description: "Tool for reverse engineering Android APK files — decode, rebuild, and resign.",
    homepage: "https://github.com/iBotPeaches/Apktool",
    license: "Apache-2.0",
    category: "reverse-engineering",
    tags: ["rev-eng", "mobile"],
    install: { kind: "brew", command: "brew install apktool", detect: "apktool" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["decompile apk", "repack apk", "android apk analysis"],
  },

  // ─── Forensics ──────────────────────────────────────────────────────────
  {
    id: "volatility3",
    name: "Volatility 3",
    description: "Memory forensics framework.",
    homepage: "https://github.com/volatilityfoundation/volatility3",
    license: "Volatility-1.0",
    category: "forensics",
    tags: ["forensics"],
    install: { kind: "pipx", command: "pipx install volatility3", detect: "vol" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["analyze memory dump", "incident response"],
  },
  {
    id: "binwalk",
    name: "Binwalk",
    description: "Firmware analysis tool.",
    homepage: "https://github.com/ReFirmLabs/binwalk",
    license: "MIT",
    category: "forensics",
    tags: ["forensics", "rev-eng"],
    install: { kind: "brew", command: "brew install binwalk", detect: "binwalk" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["analyze firmware", "extract embedded files"],
  },

  // ─── Password Cracking (authorized) ────────────────────────────────────
  {
    id: "hashcat",
    name: "Hashcat",
    description: "World's fastest GPU-accelerated password recovery tool.",
    homepage: "https://github.com/hashcat/hashcat",
    license: "MIT",
    category: "password-cracking",
    tags: ["scanner"],
    install: { kind: "brew", command: "brew install hashcat", detect: "hashcat", versionFlag: "--version" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["crack a hash (your own)", "password recovery"],
  },
  {
    id: "john",
    name: "John the Ripper",
    description: "Versatile password cracker.",
    homepage: "https://github.com/openwall/john",
    license: "GPL-2.0",
    category: "password-cracking",
    tags: ["scanner"],
    install: { kind: "brew", command: "brew install john-jumbo", detect: "john" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["crack a hash (your own)"],
  },

  // ─── SSL/TLS ─────────────────────────────────────────────────────────────
  {
    id: "testssl",
    name: "testssl.sh",
    description: "SSL/TLS configuration tester for any service on any port.",
    homepage: "https://github.com/drwetter/testssl.sh",
    license: "GPL-2.0",
    category: "ssl-tls",
    tags: ["ssl", "scanner"],
    install: { kind: "git", command: "git clone --depth 1 https://github.com/drwetter/testssl.sh", detect: "testssl.sh" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["test ssl", "check tls config", "audit certificates"],
  },

  // ─── Post-Exploitation (authorized) ────────────────────────────────────
  {
    id: "peass-ng",
    name: "PEASS-ng (LinPEAS / WinPEAS)",
    description: "Privilege escalation enumeration scripts for Linux and Windows.",
    homepage: "https://github.com/peass-ng/PEASS-ng",
    license: "MIT",
    category: "post-exploitation",
    tags: ["post-exploit"],
    install: { kind: "git", command: "git clone https://github.com/peass-ng/PEASS-ng", detect: "linpeas.sh" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["privesc enumeration", "find priv escalation paths"],
  },
  {
    id: "chisel",
    name: "Chisel",
    description: "Fast TCP/UDP tunnel, transported over HTTP, secured via SSH.",
    homepage: "https://github.com/jpillora/chisel",
    license: "MIT",
    category: "post-exploitation",
    tags: ["post-exploit"],
    install: { kind: "go", command: "go install github.com/jpillora/chisel@latest", detect: "chisel" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["tunnel traffic", "pivot through a host (authorized)"],
  },

  // ─── HTTP proxy alternatives ───────────────────────────────────────────
  {
    id: "mitmproxy",
    name: "mitmproxy",
    description: "Interactive TLS-capable intercepting HTTP proxy.",
    homepage: "https://github.com/mitmproxy/mitmproxy",
    license: "MIT",
    category: "web-attack",
    tags: ["web", "scanner", "dynamic"],
    install: { kind: "brew", command: "brew install mitmproxy", detect: "mitmproxy" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["intercept https", "modify in-flight traffic"],
  },
  {
    id: "caido",
    name: "Caido",
    description: "Modern lightweight web pentesting platform.",
    homepage: "https://github.com/caido/caido",
    license: "Caido-Free",
    category: "web-attack",
    tags: ["web", "dynamic"],
    install: { kind: "system", command: "see https://caido.io/download", detect: "caido" },
    supportedOS: ["linux", "macos", "windows"],
    intents: ["lightweight burp alternative"],
  },
];

export const BUILTIN_TOOL_COUNT = BUILTIN_TOOLS.length;
